import React from 'react';

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta content="description" name="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
