import { Inter, Roboto } from 'next/font/google'
import { ReactNode } from 'react'

import Footer from '@/views/Footer'
import Header from '@/views/Header'
import Main from '@/views/Main'
import '../common/globals.css'

export const metadata = {
  title: 'Ecommerce NextJS 13',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-roboto'
})

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className={`${roboto.className} font-sans`}>
          <Header />
          <Main />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
