import { ReactNode } from 'react';
import '../common/globals.css';
import Footer from '@/components/Footer';
import { Rubik } from 'next/font/google';

export const metadata = {
  title: 'Ecommerce NextJS 13',
  description: 'Generated by create next app',
};

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className={`${rubik.variable} font-sans`}>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
